---
dependencies:
  - role: adduser
    user: "{{ addusers.etcd }}"
    when: ansible_os_family != 'CoreOS'
  - role: download
    file: "{{ downloads.etcd }}"
    when: etcd_deployment_type == "host"
  - role: container_engine
    when: (ansible_os_family != "CoreOS" and etcd_deployment_type == "docker")
