---
- name: restart docker
  command: /bin/true
  notify:
    - reload systemd
    - reload docker

- name : reload systemd
  shell: systemctl daemon-reload
  when: ansible_service_mgr == "systemd"

- name: reload docker
  service:
    name: docker
    state: restarted
