apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-default-volume
spec:
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: gluster
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
